name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 0.2.*

env:
  TODO: >-
    --deb-changelog 
  DEB_FPM_OPTS: >-
    --prefix '/'
  COMMON_FPM_OPTS: >-
    -s dir
    -n poppy-filters
    --verbose
    -a native
    --description 'Poppy is a Rust crate offering an efficient implementation of Bloom filters. It also includes a command-line utility (also called poppy) allowing users to effortlessly create filters with their desired capacity and false positive probability. Values can be added to the filters via standard input, facilitating the use of this tool in a pipeline workflow.'
    --url 'https://github.com/hashlookup/poppy'
    --license 'BSD-3-Clause'
  PY_COMMON_FPM_OPTS: >-
    -s python
    -n python3-poppy-filters
    --verbose
    -d 'poppy-filters'
    --description 'This is a package providing python bindings for poppy, a bloom filter library written in Rust.'
    --url 'https://github.com/hashlookup/poppy'
    --license 'BSD-3-Clause'

jobs:
  release-packages:
    name: Release DEB Package
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 64

      - name: Install Dependencies
        run: |
          sudo apt install -y git build-essential cargo-1.85 rustc-1.85 pipenv
          sudo ln -s /usr/bin/cargo-1.85 /usr/bin/cargo
          sudo ln -s /usr/bin/rustc-1.85 /usr/bin/rustc

      - name: Set env variables
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
          echo "ITERATION=$(cat ITERATION)" >> $GITHUB_ENV

      - name: Tag version and push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag "v${{ env.VERSION }}-${{ env.ITERATION }}" --force
          git push origin "v${{ env.VERSION }}-${{ env.ITERATION }}" --tag --force

      - name: Build
        run: |
          git clone -b "poppy-filters-v${{ env.VERSION }}" https://github.com/hashlookup/poppy.git
          cd poppy
          RUSTFLAGS="-Ctarget-feature=+crt-static" cargo build --release --bins --target x86_64-unknown-linux-gnu

      - name: Make DEB release directory
        env:
          Build_Version: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
        run: |
          mkdir release
          mkdir release/usr
          mkdir release/usr/bin
          mkdir release/usr/share
          mkdir release/usr/share/poppy
          cp poppy/target/x86_64-unknown-linux-gnu/release/poppy release/usr/bin/
          cp poppy/LICENSE release/usr/share/poppy/
          cp poppy/README.md release/usr/share/poppy/
          ls -ailR release

      - name: Package DEB
        continue-on-error: false
        uses: bpicode/github-action-fpm@v0.9.3
        with:
          fpm_args: '.'
          fpm_opts: '-t deb -v ${{ env.VERSION }} --iteration ${{ env.ITERATION }} -C release ${{ env.COMMON_FPM_OPTS }} ${{ env.DEB_FPM_OPTS }}'

      - name: Python Build
        run: |
          cd poppy/python
          mkdir .venv
          python3 -m pipenv install
          python3 -m pipenv install 'maturin==1.9.1'
          .venv/bin/maturin build --release --target x86_64-unknown-linux-gnu
          .venv/bin/maturin develop --release --target x86_64-unknown-linux-gnu
          
      - name: Make python DEB release directory
        env:
          Build_Version: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
        run: |
          cd poppy/python
          mkdir release
          mkdir release/usr
          mkdir release/usr/lib
          mkdir release/usr/lib/python3
          mkdir release/usr/lib/python3/dist-packages
          mkdir release/usr/share
          mkdir release/usr/share/python3-poppy-filters
          cp -r .venv/lib/python3.10/site-packages/poppy release/usr/lib/python3/dist-packages/
          cp -r .venv/lib/python3.10/site-packages/poppy_py-${{ env.VERSION }}.dist-info release/usr/lib/python3/dist-packages/
          cp ../poppy/LICENSE release/usr/share/python3-poppy-filters/
          cp poppy/README.md release/usr/share/python3-poppy-filters/
          ls -ailR release

      - name: Package python DEB
        continue-on-error: false
        uses: bpicode/github-action-fpm@v0.9.3
        with:
          fpm_args: '.'
          fpm_opts: '-t deb -v ${{ env.VERSION }} --iteration ${{ env.ITERATION }} -C release ${{ env.PY_COMMON_FPM_OPTS }} ${{ env.DEB_FPM_OPTS }}'

      - name: Release
        continue-on-error: false
        uses: softprops/action-gh-release@v2.0.6
        with:
          tag_name: v${{ env.VERSION }}-${{ env.ITERATION }}
          name: |
            ${{ env.VERSION }}-${{ env.ITERATION }}
          files: |
            ./*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment the value inside ITERATION
        continue-on-error: false
        run: |
          bash ./up_iteration.sh
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "increment the ITERATION" ITERATION
          git push origin
